name: pj0y1's writing here

description: Testing.

author: pj0y1

baseurl: 

url: http://localhost:4000

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

exclude: [vendor]

permanlink: /:year/:month/:day/:title.html
